---
version: 2
registries:
  gradle-artifactory1:
    type: maven-repository
    url: https://acme.jfrog.io/artifactory/my-gradle-registry
    username: octocat
    password: ${{secrets.MY_ARTIFACTORY_PASSWORD}}
# registries:
#   seismic-registry:
#     type: npm-registry
#     url: https://registry.npmjs.org
updates:
  # - package-ecosystem: "github-actions"
  #   directory: "/javascript"
  #   schedule:
  #     interval: "daily"
  - package-ecosystem: npm
    directory: "/javascript"
    target-branch: feature/test-dependabot
    registries: "*"
    schedule:
      interval: "daily"
