---
version: 2
# registries:
#   seismic-registry:
#     type: npm-registry
#     url: https://registry.npmjs.org
    # token: ${{secrets.MY_NPM_PASSWORD}}
    # replaces-base: true
updates:
  # - package-ecosystem: "github-actions"
  #   directory: "/javascript"
  #   schedule:
  #     interval: "daily"
  - package-ecosystem: npm
    directory: "/javascript"
    target-branch: feature/test-dependabot
    allow: 
      - dependency-name: "@seismic/*"
      - dependency-name: "seismic-*"
    # registries:
    #   - seismic-registry
    schedule:
      interval: "daily"
    groups:
      prod-dependencies:
        # dependency-type: "production"
        # applies-to: version-updates
        patterns:
          - "react"
          - "react-dom"
      dev-dependencies:
        # dependency-type: "development"
        # applies-to: version-updates
        patterns:
          - "axios"
          - "eslint"
