---
version: 2
# registries:
#   seismic-registry:
#     type: npm-registry
#     url: https://registry.npmjs.org
updates:
  # - package-ecosystem: "github-actions"
  #   directory: "/javascript"
  #   schedule:
  #     interval: "daily"
  - package-ecosystem: npm
    directory: "/javascript"
    target-branch: feature/test-dependabot
    registries: "*"
    schedule:
      interval: "daily"
